### PR TITLE
Swallow getLayoutMap() error 

### LINKED ISSUE #2789: Chrome error when EditorJs is loaded in an iframe
See https://github.com/codex-team/editor.js/issues/2675.

This issue is preventing use of the library when inside of an iframe that is out of our control.

### PR DESCRIPTION
**Pull request by damacisaac**
Fail gracefully when `getLayoutMap()` throws due to being run in an insecure context. We will fallback to the given `fallback` if this happens.

This fixes #2789

### CODE REVIEW

**Comment by damacisaac** [comment]
@neSpecc @gohabereg @TatianaFomina @ilyamore88, anyone available for a review? I've had to fork the repo in the meantime

**Comment by neSpecc** [comment]
@damacisaac thanks, I'll check it soon

**Comment by damacisaac** [comment]
fixed the linting errors. should be good now

**Comment by damacisaac** [comment]
@neSpecc could you trigger another run?

**Comment by damacisaac** [comment]
Looks like a flakey attempt @neSpecc

**Comment by damacisaac** [comment]
@TatianaFomina are you perhaps able to get this in? Sorry to push, just that we've had to implement some unsightly workarounds to get past this issue for the moment.

**Review by neSpecc — APPROVED** [review]

**Comment by damacisaac** [comment]
Appreciate at it @neSpecc !

**Pull request merged**
