### PR TITLE
Stop click propagation only if click cause action

### LINKED ISSUE #1051: Remove div.codex-editor__redactor click listener
I have some components that I built using React inside Editor JS and everything's working smoothly except for the fact that the div.codex-editor__redactor has a click listener, so the onClick for the div holding my React component is not registering. 

I can remove the listener on chrome, but that's not going to be a "universal" browser solution. So, is there a way to remove this listener for all browsers? 

Thanks, I really appreciate this! I love Editor JS!!!

### PR DESCRIPTION
**Pull request by gohabereg**
Resolves #1051 #946

### CODE REVIEW

**Comment by robonetphy** [comment]
Hi @gohabereg,
I want to test this PR so to reproduce the problem I follow the below step:

- Started with create-react-app
- yarn add <user>/<repo>#<id>/head for installing this in to yarn
- And Implemented following [this](https://codesandbox.io/s/solitary-night-96hzk?fontsize=14&file=/src/index.js:0-1716)
But I am getting Error here as follow
image
Can you help me to solve the problem!.

**Comment by gohabereg** [comment]
Hi @robonetphy 
Hard to tell something from this image. Seems something is not exported/imported correctly
Can you provide a repo or archive so I can check it on my PC?

**Comment by robonetphy** [comment]
[Here](https://github.com/robonetphy/editorjs_prtesting) is my code.

**Comment by gohabereg** [comment]
Hi @robonetphy 
Your code is not correct — you are using `@editorjs/editorjs` as a React component whereas it's not.
However, I've fixed your example using `@natterstefan/reract-editor-js` and click is propagated just fine. There some issue with react re-render, but it is not related to Editor.

@neSpecc @khaydarov 
This PR is tested, we can merge it if there is no other obstacles

**Review by neSpecc — CHANGES_REQUESTED** [review]
was not tested by anybody

**Review by robonetphy — APPROVED** [review]

**Review by neSpecc — APPROVED** [review]

**Pull request merged**
