### PR TITLE
Prevent the leak of codex-tooltip when Editor.js is destroyed

### PR DESCRIPTION
**Pull request by hata6502**
https://github.com/codex-team/editor.js/issues/1475
https://github.com/codex-team/codex.tooltips/pull/7

### CODE REVIEW

**Review by neSpecc — APPROVED** [review]

**Comment by hata6502** [comment]
Resolved the conflicts.

**Review by gohabereg — APPROVED** [review]

**Comment by gohabereg** [comment]
Hi @hata6502 
Could you please resolve conflicts, we'd like to merge this one

**Comment by hata6502** [comment]
Resolved!🚀

**Comment by gohabereg** [comment]
Sorry @hata6502 , there are conflicts again 😔

**Comment by hata6502** [comment]
Done!
Conflict means Editor.js is improved frequently :)

**Comment by gohabereg** [comment]
@hata6502 
Since this one is merged #1601 Tooltip is not a module anymore, so `destroy` won't be called automatically

**Comment by hata6502** [comment]
Fixed, and I confirmed it works.
Please re-review.

**Review by gohabereg — APPROVED** [review]

**Comment by hata6502** [comment]
Would you merge this?

**Pull request merged**
