### PR TITLE
Do not use bubbling on blockManagers' listener

### PR DESCRIPTION
**Pull request by khaydarov**
Within 2.19 release, in particular in [ReadOnly](https://github.com/codex-team/editor.js/pull/1364) PR we added `useCapture` flag on one of the event listeners. Due to this flag plugins can not handle their events correctly. This PR prevents bubbling

Resolves https://github.com/codex-team/editor.js/issues/1386

### CODE REVIEW

**Review by neSpecc — CHANGES_REQUESTED** [review]
Pls fill the description and add a changelog

**Comment by robonetphy** [comment]
@neSpecc is this expected behaviour?

https://user-images.githubusercontent.com/23169768/109527370-93237b00-7ad9-11eb-9d0a-4778b01c58e6.mp4

**Comment by khaydarov** [comment]
@robonetphy No. I'll check, thanks

**Comment by talyguryn** [comment]
bug report.

- reload the page
- click at the end of the editor
- click to the image capture
- press enter

and we have error and a new line in caption

https://user-images.githubusercontent.com/15259299/110678387-50535880-81e7-11eb-8ab0-962bbc70970e.mov

**Review by talyguryn — APPROVED** [review]

**Pull request merged**
