### PR TITLE
Fix settings box-sizing

### PR DESCRIPTION
**Pull request by hata6502**
https://github.com/codex-team/editor.js/issues/1003

### CODE REVIEW

**Comment by hata6502** [comment]
Is there any problem in this PR?

**Comment by JustTSK** [comment]
@neSpecc Can you merge this please? I have the same issue with controls

**Comment by hata6502** [comment]
@neSpecc To merge this PR, what should I do?

**Comment by gohabereg** [comment]
Hi @hata6502 

Could you please update the bundle using `yarn build` command and commit it to the PR?

We will test and merge all PRs on Saturday and release new version

**Comment by hata6502** [comment]
Sorry for my mistake. 
`yarn build` and committed.

**Comment by neSpecc** [comment]
@hata6502 can you open your fork's branch for pushes so i can push some changes?

**Comment by hata6502** [comment]
Screenshot from 2020-03-15 03-54-46

I knew this useful function the first time! 
I allowed edits from maintainers.

**Pull request merged**
