### PR TITLE
Fix i18n for tunes and tools

### LINKED ISSUE #1661: [Bug] i18n for default tunes not working
Describe a bug.

Steps to reproduce:
1. Follow [your tutorial on 18n](https://editorjs.io/internationalization) to translate block tunes
2. Realize it does not work

Other translations from the tutorial work well

the version I use is `2.20.2`

```
...
      blockTunes: {
        "delete": {
          "Delete": "Удалить"
        },
        "moveUp": {
          "Move up": "Переместить вверх"
        },
        "moveDown": {
          "Move down": "Переместить вниз"
        }
      },
...
```

Expected behavior: it works

Screenshots:

Снимок экрана 2021-04-16 в 20 09 57

Снимок экрана 2021-04-16 в 20 12 47

Device, Browser, OS: macos chrome

Editor.js version: `2.20.2`

Plugins you use with their versions:

paragraph 2.8.0
header 2.6.1
image 2.6.0

### PR DESCRIPTION
**Pull request by talyguryn**
We need to call isTune function to get result

resolves #1661

### CODE REVIEW

**Comment by neSpecc** [comment]
Thanks. I've no questions about a code, but I want to test it before approve.

**Review by UmangRobro — CHANGES_REQUESTED** [review]
Also, we need to change the dictionary during initialization can you please add below code.
 
    if (dictionary.blockTunes) {
         const newBlockTunes = {};
        for (const tune in dictionary.blockTunes) {
          if (['delete', 'moveUp', 'moveDown'].includes(tune)) {
            newBlockTunes[`${tune}Tune`] = dictionary.blockTunes[tune];
          } else {
            newBlockTunes[tune] = dictionary.blockTunes[tune];
          }
        }
        dictionary.blockTunes = newBlockTunes;
      }

[here](https://github.com/codex-team/editor.js/blob/9e25400bf82c3f9e39a401e6b8dcd5ec0dd32efd/src/components/i18n/index.ts#L48)

**Comment by talyguryn** [comment]
> Also, we need to change the dictionary during initialization can you please add below code.
> 
> ```
> if (dictionary.blockTunes) {
>      const newBlockTunes = {};
>     for (const tune in dictionary.blockTunes) {
>       if (['delete', 'moveUp', 'moveDown'].includes(tune)) {
>         newBlockTunes[`${tune}Tune`] = dictionary.blockTunes[tune];
>       } else {
>         newBlockTunes[tune] = dictionary.blockTunes[tune];
>       }
>     }
>     dictionary.blockTunes = newBlockTunes;
>   }
> ```
> 
> [here](https://github.com/codex-team/editor.js/blob/9e25400bf82c3f9e39a401e6b8dcd5ec0dd32efd/src/components/i18n/index.ts#L48)

why?

**Comment by robonetphy** [comment]
because as per the documentation we will get the dictionary as follow:

    blockTunes: {
            /**
             * Each subsection is the i18n dictionary that will be passed to the corresponded Block Tune plugin
             * The name of a plugin should be equal the name you specify in the 'tunes' section for that plugin
             *
             * Also, there are few internal block tunes: "delete", "moveUp" and "moveDown"
             */
            "delete": {
              "Delete": "Удалить"
            },
            "moveUp": {
              "Move up": "Переместить вверх"
            },
            "moveDown": {
              "Move down": "Переместить вниз"
            }
          },

but due class name changes 
`delete` becomes `deleteTune`
`moveUp` becomes `moveUpTune`
and so on..
And that why it's not working

**Review by robonetphy — APPROVED** [review]
@talyguryn Sorry I didn't check that you have rename the classes

**Review by neSpecc — APPROVED** [review]

**Pull request merged**
