### PR TITLE
Fix for EditorJS nesting

### PR DESCRIPTION
**Pull request by hata6502**
By nesting Editor.js, it can design layouts more flexibly. 
I fixed some event handlers to nest Editor.js. 

**Demo**
https://codesandbox.io/s/editor-js-grid-nest-ro2uz?fontsize=14&hidenavigation=1&theme=dark

### CODE REVIEW

**Comment by hata6502** [comment]
https://github.com/codex-team/editor.js/issues/708
https://github.com/codex-team/editor.js/issues/803

**Comment by hata6502** [comment]
I saw the proposal that make Editor.js nestable, some times.
But, I want to keep Editor.js simple. 

So, I developed the plugin to nest Editor.js instance. 
https://ro2uz.csb.app/
https://www.npmjs.com/package/editor-js-grid
This solution makes Editor.js nestable with no Editor.js's function extension.

**Comment by hata6502** [comment]
Wait... This PR may be not needed by using Shadow DOM in my plugin. 
I'll try it, and close this PR if succeeded.

**Comment by Xerathron** [comment]
@hata6502 Unfortunately your links run into a 404. I would be very pleased if you can fix this :) Greetings

**Comment by hata6502** [comment]
Sorry, I couldn't find another solution. 
So, I reopened it.

**Comment by hata6502** [comment]
@Xerathron
Sorry, I needed to remove editor-js-grid, so the links are 404. 
But, this PR is useful for another issue: https://github.com/codex-team/editor.js/issues/1212

**Comment by gohabereg** [comment]
Hi there
We have a proposal for custom layouts — https://github.com/codex-team/editor.js/issues/836. 
We think nesting Editor.js instances is not the best solution for this issue. This feature should be designed from scratch and implemented as part of the core. If you would like to contribute we are happy to help!

I'm closing PR and related issues for now.

**Comment by hata6502** [comment]
@gohabereg 
Thank you for considering about layout scheme!
I think nesting Editor.js instances is difficult to use and low efficiently way, too.

**Comment by hata6502** [comment]
Editor.js can be nested by using iframe!
So this PR is not needed. 
https://github.com/hata6502/editorjs-inline/commit/3cd107eb386f9a7f4a00e980c8ce989231d334c8
Screenshot from 2020-08-29 18-29-40

**Comment by miko007** [comment]
@hata6502 do you think it is possible to apply those fixes without changing editorjs itself? like through the api or class inheritance or something?

i really need this functionality, and everything would be fine if your fixes were applied. but i certainly can not run a modified editorjs version...

**Comment by hata6502** [comment]
@miko007 
I think the Editor.js nesting is not a efficient way. 
I've seen some bugs at event listener and drag'n'drop, and so on by Editor.js nesting. 

You can try using it: 
```
yarn add impact-blue/editor.js#fix-for-nesting
```

**Comment by miko007** [comment]
thank you for your suggestion. i certainly could use your repo, but i imagine you do not fancy maintaining it, just for the sake of one guy using it.

i am not in need of an efficient solution, but one that works. On the other hand, if those changes do not interfere with regular `editorJS` usage, i do not see any reason to not merge them, as it would not hurt somebody.

For my usecase this is the ideal solution, as all other solutions just do html/css trickery for achieving columns, but i need a true nested editor with nested blocks, because i do not use editorjs to generate HTML but PDFs, where flexbox etc. is useless.

With your changes i am able to achieve all goals for the project. Nevertheless it would be nice to use the upstream version of editorjs.

**Comment by hata6502** [comment]
editor-js-grid is revived as editorjs-layout!
See: https://github.com/hata6502/editorjs-layout

**Comment by evanjmg** [comment]
Could this be revisited resolve this issue with Shadow dom etc? https://github.com/codex-team/editor.js/discussions/1881 @hata6502 ?

**Pull request closed without merging**
