### PR TITLE
fix(types): fix typescript compiler errors under strict mode

### PR DESCRIPTION
**Pull request by rajwilkhu**
This is relate to issue #2209

### CODE REVIEW

**Comment by rajwilkhu** [comment]
@here, any way to get this reviewed? It's a minor change? @neSpecc @gohabereg @TatianaFomina @ilyamore88

**Comment by neSpecc** [comment]
I think it is not the only error under strict mode. We should enable it in our tsconfig and fix all errors complexly.

**Comment by neSpecc** [comment]
But we can accept your change and release a patch anyway if your work relies on this.

**Comment by neSpecc** [comment]
Could you add a changelog, please?

**Comment by CODE-BR3AKER** [comment]
@neSpecc please merge this PR asap this issue is breaking our prod, even the --skipLibCheck has no effect on the .ts files , we have to disbale typecheck for the entire project which is bad !

**Comment by neSpecc** [comment]
Thanks for the fix. Unfortunately, I was not able to push to your branch due to disabled access for maintainers.

So I'm focusing on the similar PR [#2264](https://github.com/codex-team/editor.js/pull/2264) and closing this PR as duplicate.

**Pull request closed without merging**
