### PR TITLE
feat: support new "block-updated" event. (#2221)

### PR DESCRIPTION
**Pull request by lijie1129**
#2221

### CODE REVIEW

**Comment by lijie1129** [comment]
## Why does it need to support a single event

Recently, I tried to make a binding between the YJS and EditorJS.

This is to realize an idea. Please refer to [here](https://discuss.yjs.dev/t/editor-js-bindings/1349/5?u=jarone).

### First
Since the synchronization EditorJS changes to the data model (YJS doc) is triggered by `onChange`.

It is necessary to minimize unnecessary events and avoid performance waste.

### Second
In the scenario of multi-person collaborative editing, directly removing and replacing the DOM of the entire block will cause the collaborator to lose the input focus, which will cause experience problems. 

Therefore, it is a good way to delegate the work of updating a specific block content to a specific plug-in.

**Comment by neSpecc** [comment]
Thanks, @lijie1129, it is nice feature and implementation. 

We're working on collaborative editing, but we have not designed Tools API change yet. So adding a `update` method should be agreed. 

Do you have a workaround for a while?

**Comment by lijie1129** [comment]
Hi, @neSpecc 

Thank you for your suggestion. 🤝

I will fix this pr later.

**Comment by lijie1129** [comment]
This issue has been resolved.

**Pull request closed without merging**
