### PR TITLE
Make click event of block propagate

### PR DESCRIPTION
**Pull request by hata6502**
https://github.com/codex-team/editor.js/issues/1021

### CODE REVIEW

**Comment by neSpecc** [comment]
Thanks for the PR. Please, attach an issue that describes a problem you resolve.

**Comment by natterstefan** [comment]
Is this also related to #946 @hata6502?

**Comment by hata6502** [comment]
Yes, I also use React.

**Comment by ryandunnewold** [comment]
Running into this issue as well. Any updates here?

**Comment by dyrdzik** [comment]
The same problem on our end. We've also discovered that usually (which looks weird) buttons fire events. When having select element it does not go through. Only when you double click in block area as it makes `window.getSelection().isCollapsed` return false.

**Comment by 2277Dhruv** [comment]
Running into this issue as well. Are there any updates?!

**Comment by hata6502** [comment]
Very sorry that I didn't update this PR.
I seem this issue doesn't cause with Vanilla JS.
So, I think it is not a bug in Editor JS.

**Demo**
Listen click event correctly. 
https://codesandbox.io/s/editor-js-propagate-click-events-w5371?fontsize=14&hidenavigation=1&theme=dark

**Comment by allankikkas** [comment]
https://github.com/codex-team/editor.js/issues/1051#issuecomment-600098345

**Pull request closed without merging**
