### PR TITLE
Fix blocks.delete with undefined index (#1182)

### PR DESCRIPTION
**Pull request by stephenrichard**
In some situations `this.Editor.BlockManager.currentBlock` is not defined. (For example if the user didn't interact with the editor yet but can add/remove blocks outside via buttons using the API)

Capture d’écran 2020-07-03 à 18 22 36

When deleting a block, the Caret (cursor head in my understanding) tries to move to the currentBlock (that can be `undefined`) and trigger a legitimate error.

This PR simply adds a condition around the Caret that checks for a currentBlock :
- If it's defined, move to the currentBlock
- If not, just do not move

### CODE REVIEW

**Comment by ranemihir** [comment]
@stephenrichard can you create an issue regarding this so that we can test if the issue actually exists?

**Comment by stephenrichard** [comment]
@ranemihir Yes, sorry I forgot to link an issue to this but it refers to #1182

**Comment by ranemihir** [comment]
@stephenrichard Thank you. I will test it and let you know.

**Comment by stephenrichard** [comment]
@neSpecc Sure, how should I proceed ? I checkout this PR, edit the CHANGELOG.md and push the changes ? (It won't revoke the approvals ?)

**Pull request merged**
