### PR TITLE
Add RTL support

### PR DESCRIPTION
**Pull request by GINCHER**
Issue: https://github.com/codex-team/editor.js/issues/670

I have created `example-dev-rtl.html` with Hebrew in the editor to be able to test the RTL. To make the editor RTL, the user should add to the config `{direction: 'rtl'}`.

**Tasks done:**
- Modify CSS to support RTL
- Calculate distance from the right for the tooltip
- Right and left keys will move the user between blocks correctly
- Inline URL input field will remain LTR

### CODE REVIEW

**Comment by hoseinz3xs** [comment]
@neSpecc  @khaydarov @gohabereg Could you please review this feature? I definitely wanna this one

**Comment by neSpecc** [comment]
@hoseinz3xs sure, we will review it soon.

**Comment by GINCHER** [comment]
- Flipper now works correctly with the keyboard arrows when RTL
- Conversion window now appears on the right side

**Comment by rezam90** [comment]
@neSpecc any updates on this feature?

**Comment by neSpecc** [comment]
@rezam90 we'll try to include it to the next release.

**Comment by kfirba** [comment]
@neSpecc Is there any ETA as of when will this be merged? This seems like the only missing piece so we can use the editor in production :)

**Comment by neSpecc** [comment]
@kfirba May — June

**Comment by kfirba** [comment]
@neSpecc oh wow, that was a snappy response. Thanks!

Is it guaranteed that RTL support is coming in the next version?

**Comment by khaydarov** [comment]
@GINCHER could you re-open your PR, please? It seems to be unavailable

**Comment by arfrix** [comment]
I'll need that too

**Pull request closed without merging**
