### PR TITLE
fix $.isEmpty performance

### PR DESCRIPTION
**Pull request by tasuku-s**
#1095

### CODE REVIEW

**Comment by gohabereg** [comment]
Hi @tasuku-s 
Could you please rebase PR to `release/2.18` branch, pull it into yours and `yarn build`

**Comment by tasuku-s** [comment]
OK, I rebased it and `yarn build` is succeed.

(but yarn lint says `ESLint couldn't find the config "codex" to extend from. Please check that the name of the config is correct.`.)

**Comment by gohabereg** [comment]
I guess, you need to install packages via `yarn install`

**Comment by tasuku-s** [comment]
sorry! I could  execute lint command, and fixed error.

**Comment by khaydarov** [comment]
@tasuku-s can you add a record about your enhancement in the [changelog](https://github.com/codex-team/editor.js/blob/master/docs/CHANGELOG.md)

**Pull request merged**
