### PR TITLE
Fix flipper activate/deactivate when conversionToolbarOpened

### LINKED ISSUE #995: Cannot add items to list converted from paragraph
To reproduce:
1. Write a paragraph
2. Convert to list
3. Press the return key to add a new item to the list - it does not work

### PR DESCRIPTION
**Pull request by aablinov**
This closes #995 

I studied the problem more deeply. This happens because `flipper.ts` who intercept key down ENTER events and we do not deactivate flipper when conversion toolbar closed. This bug still reproduced not only when converting paragraph and List component it's reproduced in all components with `static get enableLineBreaks() { return true; }` such as CodeTool/List/Warning/Raw/Quote.

Step to reproduce:

1. Open https://editorjs.io/
2. Type any text or convert exist to List // this produce flipper.activate() and intercept enter key down
3. Try to create any tool Code, for example, newline break not working

Screen: https://imgur.com/a/jD1xoZP

Thanks, @next-direction for the tip

### CODE REVIEW

**Comment by VLZH** [comment]
@gohabereg @khaydarov  @neSpecc  Hello! What do you think about this PR? I would be happy if you accept this PR and fix problems with converting paragraphs to list.

**Comment by ceesvanegmond** [comment]
Seems to solve alot of problems! @gohabereg @khaydarov @neSpecc

**Comment by neSpecc** [comment]
We will check it soon. Thanks for the PR.

**Comment by ceesvanegmond** [comment]
@neSpecc I can verify that this also fixes https://github.com/codex-team/editor.js/issues/1041.

**Comment by ALITHEALI** [comment]
Any updates on this one?

**Pull request merged**
