### PR TITLE
fix: prevent inline toolbar from closing in nested instance of editor

### PR DESCRIPTION
**Pull request by gorenburg**
Based on https://github.com/codex-team/editor.js/pull/2581

Closes issue with inline toolbar being closed in the nested editor instance when clicking on the toolbar button with some actions. The fix is taken from https://github.com/codex-team/editor.js/pull/2581; this PR adds cypress tests for the fix

### CODE REVIEW

**Review by neSpecc — APPROVED** [review]
Worked fine, thanks. Please, add a line to the changelog under the  2.30.6 section

**Comment by neSpecc** [comment]
There is an ESLint error:
```
/home/runner/work/editor.js/editor.js/test/cypress/support/utils/nestedEditorInstance.ts
   1:1   error    All imports in the declaration are only used as types. Use `import type`  @typescript-eslint/consistent-type-imports
```

**Comment by gorenburg** [comment]
> There is an ESLint error:
> 
> ```
> /home/runner/work/editor.js/editor.js/test/cypress/support/utils/nestedEditorInstance.ts
>    1:1   error    All imports in the declaration are only used as types. Use `import type`  @typescript-eslint/consistent-type-imports
> ```

was fixing it the same moment you added comment 😄

**Comment by gorenburg** [comment]
Ready to ship? 😀

**Comment by calumk** [comment]
I also hope so soon ...

**Pull request merged**
