### PR TITLE
Feature/disable tab event config

### PR DESCRIPTION
**Pull request by flaming-cl**
Added an internal setting disableDefaultTabEvent to disable Editor/browser Tab Event
If users want to add their own tab event like inserting tab indents, they can disable the original tab event by using this config.

### CODE REVIEW

**Comment by neSpecc** [comment]
Great, will check it soon.

**Comment by neSpecc** [comment]
@flaming-cl Now you can add own keydown handler in your tool and override Tab behaviour

**Comment by flaming-cl** [comment]
> @flaming-cl Now you can add own keydown handler in your tool and override Tab behaviour

Great! This is much better than adding another internal setting. Thanks!!

**Comment by mkeida** [comment]
Hi! How exactly can I override default tab key behaviour? I need TAB for indents in my code block.

**Pull request merged**
