### PR TITLE
fix: use type imports for block events

### LINKED ISSUE #2373: Typescript import error (TS1444 and TS1371)
Describe a bug.

Steps to reproduce:
When I tried to build my app, the type check failed with following errors:

Expected behavior:
No build error, and develop build(npm dev run) don't show these errors.

Screenshots:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@editorjs/editorjs/types/events/block/Base.ts:1:1 - error TS1371: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.

1 import { BlockAPI } from '../../api';

node_modules/@editorjs/editorjs/types/events/block/Base.ts:1:10 - error TS1444: 'BlockAPI' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.

1 import { BlockAPI } from '../../api';

node_modules/@editorjs/editorjs/types/events/block/BlockAdded.ts:1:1 - error TS1371: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.

1 import { BlockMutationEventDetail } from './Base';

node_modules/@editorjs/editorjs/types/events/block/BlockAdded.ts:1:10 - error TS1444: 'BlockMutationEventDetail' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.

1 import { BlockMutationEventDetail } from './Base';

node_modules/@editorjs/editorjs/types/events/block/BlockChanged.ts:1:1 - error TS1371: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.

1 import { BlockMutationEventDetail } from './Base';

node_modules/@editorjs/editorjs/types/events/block/BlockChanged.ts:1:10 - error TS1444: 'BlockMutationEventDetail' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.

1 import { BlockMutationEventDetail } from './Base';

node_modules/@editorjs/editorjs/types/events/block/BlockMoved.ts:1:1 - error TS1371: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.

1 import { BlockMutationEventDetail } from './Base';

node_modules/@editorjs/editorjs/types/events/block/BlockMoved.ts:1:10 - error TS1444: 'BlockMutationEventDetail' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.

1 import { BlockMutationEventDetail } from './Base';

node_modules/@editorjs/editorjs/types/events/block/BlockRemoved.ts:1:1 - error TS1371: This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.

1 import { BlockMutationEventDetail } from './Base';

node_modules/@editorjs/editorjs/types/events/block/BlockRemoved.ts:1:10 - error TS1444: 'BlockMutationEventDetail' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.

1 import { BlockMutationEventDetail } from './Base';

node_modules/@editorjs/editorjs/types/events/block/index.ts:1:10 - error TS1444: 'BlockAddedEvent' is a type and must be imported using a type-only import when 'preserveValueImports' and 'isolatedModules' are both enabled.

1 import { BlockAddedEvent, BlockAddedMutationType } from './BlockAdded';

4 import { BlockRemovedEvent, BlockRemovedMutationType } from './BlockRemoved';
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Device, Browser, OS:
Desktop, Windows, Vite v4.3.9

Editor.js version:
2.27.0

Plugins you use with their versions:
Paragraph, AlignmentTune, NestedList, Undeline and some custom plugins (by me).

> Solution was simple for me, just add 'type' those error modules..
> like..
> import **type** { BlockMutationEventDetail } from './Base';
> but I'm not sure this solution is right.

Would you please reseach this issue?
Thank you in advance!

### PR DESCRIPTION
**Pull request by ferntheplant**
Resolves #2373 where type imports were not being used

### CODE REVIEW

**Comment by danielclausmeyer** [comment]
Can this please be updated and merged? I have to disable `verbatimModuleSyntax` in my project or else it keeps showing these errors.

**Comment by neSpecc** [comment]
Please, update a branch

**Comment by ghost** [comment]
i got same issue please checking and update them

**Comment by ryanldy** [comment]
Hi @ferntheplant. I think this is not getting merged because of a branch conflict.

Or maybe you can give me an access to push changes in this repository.

cc: @neSpecc @gohabereg @TatianaFomina @ilyamore88

**Review by neSpecc — APPROVED** [review]

**Review by ilyamore88 — APPROVED** [review]
Thanks 👍

**Review by gohabereg — APPROVED** [review]

**Comment by ryanldy** [comment]
Thank you! 😄

**Comment by ryanldy** [comment]
Just wanted to ask when will this be released? Thanks again! 😃 

cc: @neSpecc @gohabereg @TatianaFomina @ilyamore88

**Comment by neSpecc** [comment]
> Just wanted to ask when will this be released? Thanks again! 😃

You can start using it with `2.29.0-rc.7`

**Pull request merged**
