### PR TITLE
fix: RegExp in tool config

### PR DESCRIPTION
**Pull request by igorivaniuk**
without that plugin https://github.com/editor-js/embed with custom cunfig will not work

### CODE REVIEW

**Comment by gohabereg** [comment]
Hi @igorivaniuk 
Thank you for contribution!

Could you please add a note to docs/CHANGELOG.md file (under 2.15 version)

**Comment by gohabereg** [comment]
@igorivaniuk 
We found some workaround to get a variable type — https://javascriptweblog.wordpress.com/2011/08/08/fixing-the-javascript-typeof-operator/

Let us know please if you have time to implement a function (in src/component/utils.ts file) and use it to check variable type, otherwise I'll close your PR and add this function myself.

Thanks!

**Comment by igorivaniuk** [comment]
Hi @gohabereg 
I don`t know what side effects can be if i rewrite function, and there are no tests for check if all ok.
So close please my PR.

**Comment by gohabereg** [comment]
Sure
Thanks again for contribution, fix will be included to the next release

**Pull request closed without merging**
