### PR TITLE
Deleting multiple blocks triggers back button in Firefox

### PR DESCRIPTION
**Pull request by evgenusov**

### CODE REVIEW

**Comment by khaydarov** [comment]
#869

**Comment by evgenusov** [comment]
@khaydarov no. This is not the #869 issue. This is #868

**Comment by ralphschindler** [comment]
This is an issue for us as well. If this is a clean fix, merging would be appreciated! 👍

**Comment by khaydarov** [comment]
@evgenusov could you update the bundle, please?

**Pull request closed without merging**
