### PR TITLE
Move SavedData and ValidatedData interfaces from internal types

### LINKED ISSUE #1183: Error when trying to integrate Editorjs with Angular
This is the error I get: 
---------------------------------------------------------------------
ERROR in node_modules/@editorjs/editorjs/types/api/block.d.ts:2:25 - error TS2307: Cannot find module '../../src/types-internal/block-data'.

import {SavedData} from '../../src/types-internal/block-data';
---------------------------------------------------------------------

So basically it's trying to import from src folder, but there is no src folder in the @editorjs/editorjs when i use the 'npm install @editorjs/editorjs --save-dev'. 
I am aware that there is an ngx-editorjs package, but I'm really frustrated by this issue.
Any help would be highly appreciated.

### PR DESCRIPTION
**Pull request by gohabereg**
Resolves #1183

### CODE REVIEW

**Comment by danielsmeyer** [comment]
Is there a timeline for when this will go live?

**Comment by gohabereg** [comment]
Hi @danielsmeyer 
Are you able to check the fix? We are ready to merge it, but to check it we need to setup angular environment from the original issue -- it takes time

**Comment by mr-rahimi** [comment]
I would be grateful if this bugfix approved by the contributors.
@gohabereg

**Review by khaydarov — APPROVED** [review]

**Comment by danielsmeyer** [comment]
Thanks for merging this. When will this be reflected on npm?

**Comment by gohabereg** [comment]
Hey @danielsmeyer 
The main feature planned for 2.19 is read-only mode. We need to fix some issues there and then release will be published to npm.

**Comment by danielsmeyer** [comment]
Would it be possible to push an interim 2.18.1 fix with just this small type change, while 2.19 is getting ready?

**Comment by danielsmeyer** [comment]
Legends! ❤️

**Pull request merged**
